In [1]:
import numpy as np
import sympy
x, y, z, t = sympy.symbols('x y z t')

# Diferenciação Numérica

Principais formulas de diferenças finitas usando expansão em série de Taylor

### Diferença finita progressiva com dois pontos
Aproximação de Taylor para o ponto $x_{i+1}$
  $$
    f(x_{i+1}) = f(x_i) + f'(x_i)h + \frac{h^2}{2!}f''(x) + \frac{h^3}{3!}f'''(x) + ...
  $$
  com $h=x_{i+1} - x_i$.

  Fixando dois primeiro termos da serie e deixando os outros termos como um resíduo, temos,
  $$
  f(x_{i+1}) = f(x_i) + f'(x_i)h + \frac{h^2}{2!}f''(\xi )
  $$
  Isolando $f'(x)$, temos:
  $$
  f'(x_i) = \frac{f(x_{i+1}) - f(x_i)}{h} - \frac{h}{2}f''(\xi )
  $$
  com erro de truncamento,
  $$
  - \frac{h}{2}f''(\xi ) = O(h)
  $$

  ### Diferença finita regressiva com dois pontos

  Aproximação de Taylor para o ponto $x_{i-1}$
  $$
      f(x_{i-1}) = f(x_i) - f'(x_i)h + \frac{h^2}{2!}f''(x_i) - \frac{h^3}{3!}f'''(x_i) + ...
  $$
  com $h=x_{i} - x_{i-1}$.
  
  Fixando dois primeiro termos da serie e deixando os outros termos como um resíduo, temos,
  $$
    f(x_{i-1}) = f(x_i) - f'(x_i)h + \frac{h^2}{2!}f''(\xi )
  $$
  Isolando $f'(x)$, temos:
  $$
    f'(x_i) = \frac{f(x_{i}) - f(x_{i-1})}{h} + \frac{h}{2}f''(\xi )
  $$
com erro de truncamento,
  $$
       \frac{h}{2}f''(\xi ) = O(h)
  $$

## Diferença finita central com dois pontos
Aproximação de Taylor para o ponto $x_{i+1}$
$$
      f(x_{i+1}) = f(x_i) + f'(x_i)h + \frac{h^2}{2!}f''(x) + \frac{h^3}{3!}f'''(\xi_1)
$$
com $\xi_1 \in (x_{i},x_{i+1})$.
Aproximação de Taylor para o ponto $x_{i-1}$
$$
      f(x_{i-1}) = f(x_i) - f'(x_i)h + \frac{h^2}{2!}f''(x_i) - \frac{h^3}{3!}f'''(\xi_2)
$$
com $\xi_2 \in (x_{i-1},x_{i})$.
Subtraindo as equações acima, temos
$$
      f(x_{i+1}) - f(x_{i-1}) = 2hf'(x_i) + \frac{h^3}{3!}f'''(\xi_1) + \frac{h^3}{3!}f'''(\xi_2)
$$
Resolvendo para $f'(x)$, temos
$$
    f'(x_i) = \frac{f(x_{i+1}) - f(x_{i-1})}{2h} + \frac{h^2}{6}f'''(\xi )
$$
com erro de truncamento,
  $$
       \frac{h^2}{6}f'''(\xi ) = O(h^2)
  $$

## Exercício

1. Faça uma tabela do erro para as formulas de diferencias finitas acima para a aproximação de $f'(0)$, onde $f(x) = \sin(x) - \cos(x)$ com $h=10^{-1}, 10^{-2},...,10^{-10}$. O erro mínimo corresponde à expectativa teórica?



In [ ]:
# Implementando a função em questão

def f (x):
  return np.sin(x)-np.cos(x)

# Implemente uma função para diferencição progressiva: dfp
def diferencicao_progressiva(x,h):
  return (f(x)-f(x-h))/h

# Implemente uma função para diferenciação regressiva: dfr


# Implemente uma função para diferenciação central: dfc


# Criar uma tabela: h, error-dfp, error-dfr, error-dfc

In [9]:
import numpy as np 
eval = np.linspace(2015,2023,num=200,dtype=int)
eval

array([2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015,
       2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015,
       2015, 2015, 2015, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016,
       2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016,
       2016, 2016, 2016, 2016, 2016, 2016, 2017, 2017, 2017, 2017, 2017,
       2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017,
       2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2018, 2018,
       2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018,
       2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018,
       2018, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019,
       2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019,
       2019, 2019, 2019, 2019, 2020, 2020, 2020, 2020, 2020, 2020, 2020,
       2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020,
       2020, 2020, 2020, 2020, 2020, 2020, 2020, 20

In [10]:
valores_unicos, repeticoes = np.unique(eval,return_counts =True)

In [11]:
valores_unicos

array([2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023])

In [12]:
repeticoes

array([25, 25, 25, 25, 25, 25, 25, 24,  1])